name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build docker image
      run: docker build . --tag latest
    - name: push image
      run: docker push ghcr.io/moderndata-org/moderndata:latest
